"""
Export the loop's best policies into the NON-gitignored checkpoints_to_test/
folder so they can be committed from EC2 and `git pull`-ed locally for testing
in RLBot (data/ is gitignored, so checkpoints there never leave the box).

Run after a PROMOTE (or every few iterations):
  python tools/export_best.py
  git add checkpoints_to_test && git commit -m "Export V4 best (iter N)" && git push

Copies (stable filenames, overwritten each export, so the working tree stays
two ~30MB files instead of growing forever):
  checkpoints_to_test/PPO_POLICY_V4_BEST.pt    <- state.best_ever_ckpt
  checkpoints_to_test/PPO_POLICY_V4_LATEST.pt  <- state.best_ckpt (current line)
  checkpoints_to_test/STATUS.md                <- scores, config, history tail
"""
import argparse
import json
import os
import shutil

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATE = os.path.join(REPO, "data", "loop_state", "state.json")
HISTORY = os.path.join(REPO, "data", "loop_state", "history.csv")
BEST_CONFIG = os.path.join(REPO, "data", "loop_state", "best_config.json")
OUT_DIR = os.path.join(REPO, "checkpoints_to_test")


def _copy_policy(ckpt_dir, dest_name):
    if not ckpt_dir:
        return None
    src = os.path.join(REPO, ckpt_dir, "PPO_POLICY.pt")
    if not os.path.isfile(src):
        print(f"[export] WARNING: {src} missing, skipped")
        return None
    dest = os.path.join(OUT_DIR, dest_name)
    shutil.copy2(src, dest)
    print(f"[export] {src} -> {dest}")
    return ckpt_dir


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--state", default=STATE)
    args = p.parse_args()

    with open(args.state) as f:
        state = json.load(f)
    os.makedirs(OUT_DIR, exist_ok=True)

    best_ever = _copy_policy(state.get("best_ever_ckpt"), "PPO_POLICY_V4_BEST.pt")
    latest = None
    if state.get("best_ckpt") and state.get("best_ckpt") != state.get("best_ever_ckpt"):
        latest = _copy_policy(state.get("best_ckpt"), "PPO_POLICY_V4_LATEST.pt")

    lines = [
        "# V4 loop status (auto-generated by tools/export_best.py)",
        "",
        f"- iteration: {state.get('iteration')}",
        f"- BEST.pt   <- `{best_ever}`  (score {state.get('best_ever_score')})",
        f"- LATEST.pt <- `{latest or best_ever}`  (score {state.get('best_score')})",
        f"- last change tried: {state.get('last_change')}",
        "",
        "`score` = P(candidate scores | a goal) vs the Element bot;",
        "`style` = air dribbles per game (see eval_match.py).",
        "",
    ]
    if os.path.isfile(BEST_CONFIG):
        with open(BEST_CONFIG) as f:
            lines += ["## best_config.json", "```json", f.read().strip(), "```", ""]
    if os.path.isfile(HISTORY):
        with open(HISTORY) as f:
            tail = f.read().strip().splitlines()[-12:]
        lines += ["## history (last 12 iterations)", "```csv", *tail, "```", ""]
    with open(os.path.join(OUT_DIR, "STATUS.md"), "w") as f:
        f.write("\n".join(lines))
    print(f"[export] wrote {os.path.join(OUT_DIR, 'STATUS.md')}")


if __name__ == "__main__":
    main()
